name: bg_service
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  awesome_notifications: ^0.8.2
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  workmanager: ^0.5.2
  google_maps_flutter: ^2.6.0
  http: ^1.2.2
  location: ^6.0.2
  flutter_polyline_points: ^2.1.0
  flutter_background: ^1.3.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/ic_launcher.png
    - assets/gas_station_icon.png

  plugin:
    platforms:
      android:
        package: com.example.bg_service
        pluginClass: bg_service

